apiVersion: apps/v1
kind: Deployment
metadata:
  name: caalbert
  labels:
    app: caalbert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caalbert
  template:
    metadata:
      labels:
        app: caalbert
    spec:
      containers:
        - name: caalbert
          image: tonnytg/caalbert42:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
